#define WS2812_DI_PIN GP23
#define WS2812_PIO_USE_PIO1
#define RGB_MATRIX_LED_COUNT 62
#define RGB_MATRIX_SLEEP true

//For test only
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_CYCLE_LEFT_RIGHT
#define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
